/////////////////////////////////////////////////////////////////////////////
// Name:        connectmanagerdlg.h
// Purpose:     
// Author:      CodeSoul
// Modified by: 
// Created:     01/06/2015 23:05:40
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 01/06/2015 23:05:40

#ifndef _CONNECTMANAGERDLG_H_
#define _CONNECTMANAGERDLG_H_


/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_CONNECTMANAGERDLG 10000
#define ID_LISTBOX 10001
#define ID_BTN_CLOSE 10002
#define SYMBOL_CONNECTMANAGERDLG_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_CONNECTMANAGERDLG_TITLE _("Connect Manager")
#define SYMBOL_CONNECTMANAGERDLG_IDNAME ID_CONNECTMANAGERDLG
#define SYMBOL_CONNECTMANAGERDLG_SIZE wxSize(400, 300)
#define SYMBOL_CONNECTMANAGERDLG_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * ConnectManagerDlg class declaration
 */

class ConnectManagerDlg: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( ConnectManagerDlg )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    ConnectManagerDlg();
    ConnectManagerDlg( wxWindow* parent, wxWindowID id = SYMBOL_CONNECTMANAGERDLG_IDNAME, const wxString& caption = SYMBOL_CONNECTMANAGERDLG_TITLE, const wxPoint& pos = SYMBOL_CONNECTMANAGERDLG_POSITION, const wxSize& size = SYMBOL_CONNECTMANAGERDLG_SIZE, long style = SYMBOL_CONNECTMANAGERDLG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_CONNECTMANAGERDLG_IDNAME, const wxString& caption = SYMBOL_CONNECTMANAGERDLG_TITLE, const wxPoint& pos = SYMBOL_CONNECTMANAGERDLG_POSITION, const wxSize& size = SYMBOL_CONNECTMANAGERDLG_SIZE, long style = SYMBOL_CONNECTMANAGERDLG_STYLE );

    /// Destructor
    ~ConnectManagerDlg();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

	void UpdateList();

////@begin ConnectManagerDlg event handler declarations

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BTN_CLOSE
    void OnBtnCloseClick( wxCommandEvent& event );

////@end ConnectManagerDlg event handler declarations

////@begin ConnectManagerDlg member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end ConnectManagerDlg member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin ConnectManagerDlg member variables
    wxListBox* m_listConnect;
    wxButton* m_btnClose;
////@end ConnectManagerDlg member variables
};

#endif
    // _CONNECTMANAGERDLG_H_
