/////////////////////////////////////////////////////////////////////////////
// Name:        maindlg.h
// Purpose:     
// Author:      CodeSoul
// Modified by: 
// Created:     28/05/2015 02:26:07
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 28/05/2015 02:26:07

#ifndef _MAINDLG_H_
#define _MAINDLG_H_


/*!
 * Includes
 */

////@begin includes
////@end includes

#include "wx/socket.h"

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_MAINDLG 10000
#define ID_BTN_LISTEN 10001
#define ID_BTN_MANAGER 10005
#define ID_TEXT_PORT 10004
#define ID_TEXT_LOG 10002
#define ID_BUT_MYSQL 10003
#define SYMBOL_MAINDLG_STYLE wxCAPTION|wxSYSTEM_MENU|wxCLOSE_BOX|wxMINIMIZE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_MAINDLG_TITLE _("MainDlg")
#define SYMBOL_MAINDLG_IDNAME ID_MAINDLG
#define SYMBOL_MAINDLG_SIZE wxSize(400, 300)
#define SYMBOL_MAINDLG_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * MainDlg class declaration
 */

class MainDlg: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( MainDlg )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    MainDlg();
    MainDlg( wxWindow* parent, wxWindowID id = SYMBOL_MAINDLG_IDNAME, const wxString& caption = SYMBOL_MAINDLG_TITLE, const wxPoint& pos = SYMBOL_MAINDLG_POSITION, const wxSize& size = SYMBOL_MAINDLG_SIZE, long style = SYMBOL_MAINDLG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_MAINDLG_IDNAME, const wxString& caption = SYMBOL_MAINDLG_TITLE, const wxPoint& pos = SYMBOL_MAINDLG_POSITION, const wxSize& size = SYMBOL_MAINDLG_SIZE, long style = SYMBOL_MAINDLG_STYLE );

    /// Destructor
    ~MainDlg();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

	void StartListen();
////@begin MainDlg event handler declarations

    /// wxEVT_INIT_DIALOG event handler for ID_MAINDLG
    void OnInitDialog( wxInitDialogEvent& event );

    /// wxEVT_CLOSE_WINDOW event handler for ID_MAINDLG
    void OnCloseWindow( wxCloseEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BTN_LISTEN
    void OnBtnListenClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BTN_MANAGER
    void OnBtnManagerClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUT_MYSQL
    void OnButMysqlClick( wxCommandEvent& event );

////@end MainDlg event handler declarations

////@begin MainDlg member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end MainDlg member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin MainDlg member variables
    wxButton* m_btnListen;
    wxButton* m_manager;
#if defined(__WXMSW__)
    wxTextCtrl* m_txPort;
#endif
    wxTextCtrl* m_txLog;
    wxButton* m_btnMySql;
////@end MainDlg member variables
};

class ThreadConnect : public wxThread
{
	static int MAX_LENGTH;
	static wxCriticalSection CriSec;
public:
	ThreadConnect(wxSocketBase* connect) : wxThread() { m_connect = connect; }
	~ThreadConnect();
	wxSocketBase *m_connect;
	void OnExit();
protected:
	virtual ExitCode Entry();
	char * m_buf;
};

class ThreadListen : public wxThread
{
public:
	ThreadListen(unsigned int port) : wxThread() , m_port(port) {}
protected:
	virtual ExitCode Entry();
private:
	unsigned int m_port;
};

#endif
    // _MAINDLG_H_
