/////////////////////////////////////////////////////////////////////////////
// Name:        mysqldlg.h
// Purpose:     
// Author:      CodeSoul
// Modified by: 
// Created:     02/06/2015 20:35:16
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 02/06/2015 20:35:16

#ifndef _MYSQLDLG_H_
#define _MYSQLDLG_H_


/*!
 * Includes
 */

////@begin includes
////@end includes
#include "SqlConnector.h"

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_MYSQLDLG 10000
#define ID_TEXT_RESULT 10001
#define ID_TEXT_SQL 10002
#define ID_BTN_CONNECT_MYSQL 10003
#define ID_BUT_EXEC 10004
#define ID_BUT_CONF 10005
#define ID_PANEL_CONFIG 10010
#define ID_TEXT_SERVER 10006
#define ID_TEXT_USER 10007
#define ID_TEXT_PORT 10008
#define ID_TEXT_PASSWD 10009
#define SYMBOL_MYSQLDLG_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_MYSQLDLG_TITLE _("MySqlDlg")
#define SYMBOL_MYSQLDLG_IDNAME ID_MYSQLDLG
#define SYMBOL_MYSQLDLG_SIZE wxSize(400, 300)
#define SYMBOL_MYSQLDLG_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * MySqlDlg class declaration
 */

class MySqlDlg: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( MySqlDlg )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    MySqlDlg();
    MySqlDlg( wxWindow* parent, wxWindowID id = SYMBOL_MYSQLDLG_IDNAME, const wxString& caption = SYMBOL_MYSQLDLG_TITLE, const wxPoint& pos = SYMBOL_MYSQLDLG_POSITION, const wxSize& size = SYMBOL_MYSQLDLG_SIZE, long style = SYMBOL_MYSQLDLG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_MYSQLDLG_IDNAME, const wxString& caption = SYMBOL_MYSQLDLG_TITLE, const wxPoint& pos = SYMBOL_MYSQLDLG_POSITION, const wxSize& size = SYMBOL_MYSQLDLG_SIZE, long style = SYMBOL_MYSQLDLG_STYLE );

    /// Destructor
    ~MySqlDlg();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin MySqlDlg event handler declarations

    /// wxEVT_CLOSE_WINDOW event handler for ID_MYSQLDLG
    void OnCloseWindow( wxCloseEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BTN_CONNECT_MYSQL
    void OnBtnConnectMysqlClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUT_EXEC
    void OnButExecClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUT_CONF
    void OnButConfClick( wxCommandEvent& event );

////@end MySqlDlg event handler declarations

////@begin MySqlDlg member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end MySqlDlg member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin MySqlDlg member variables
    wxTextCtrl* m_txResult;
    wxTextCtrl* m_txSql;
    wxButton* m_btnConnect;
    wxButton* m_btnExec;
    wxButton* m_btnConf;
    wxPanel* m_paneConf;
    wxTextCtrl* m_server;
    wxTextCtrl* m_txUser;
    wxTextCtrl* m_txPort;
    wxTextCtrl* m_txPasswd;
////@end MySqlDlg member variables
	MySql  m_mysql;
};

#endif
    // _MYSQLDLG_H_
