/////////////////////////////////////////////////////////////////////////////
// Name:        connectdlg.h
// Purpose:     
// Author:      CodeSoul
// Modified by: 
// Created:     29/05/2015 10:33:48
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 29/05/2015 10:33:48

#ifndef _CONNECTDLG_H_
#define _CONNECTDLG_H_


/*!
 * Includes
 */

////@begin includes
////@end includes

#include "wx/socket.h"

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_CONNECTDLG 10000
#define ID_TEXT_CONTENT 10001
#define ID_BTN_SEND 10002
#define SYMBOL_CONNECTDLG_STYLE wxCAPTION|wxSYSTEM_MENU|wxCLOSE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_CONNECTDLG_TITLE _("ConnectDlg")
#define SYMBOL_CONNECTDLG_IDNAME ID_CONNECTDLG
#define SYMBOL_CONNECTDLG_SIZE wxSize(400, 300)
#define SYMBOL_CONNECTDLG_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * ConnectDlg class declaration
 */

class ConnectDlg: public wxDialog
{    
    //DECLARE_DYNAMIC_CLASS( ConnectDlg )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    ConnectDlg(wxString& ip, unsigned int port) { m_ip = wxString(ip);
												m_port = port;
												Create(NULL); }
    ConnectDlg( wxWindow* parent, wxWindowID id = SYMBOL_CONNECTDLG_IDNAME, const wxString& caption = SYMBOL_CONNECTDLG_TITLE, const wxPoint& pos = SYMBOL_CONNECTDLG_POSITION, const wxSize& size = SYMBOL_CONNECTDLG_SIZE, long style = SYMBOL_CONNECTDLG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_CONNECTDLG_IDNAME, const wxString& caption = SYMBOL_CONNECTDLG_TITLE, const wxPoint& pos = SYMBOL_CONNECTDLG_POSITION, const wxSize& size = SYMBOL_CONNECTDLG_SIZE, long style = SYMBOL_CONNECTDLG_STYLE );

    /// Destructor
    ~ConnectDlg();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin ConnectDlg event handler declarations

    /// wxEVT_CLOSE_WINDOW event handler for ID_CONNECTDLG
    void OnCloseWindow( wxCloseEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BTN_SEND
    void OnBtnSendClick( wxCommandEvent& event );

////@end ConnectDlg event handler declarations

////@begin ConnectDlg member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end ConnectDlg member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin ConnectDlg member variables
    wxTextCtrl* m_txContent;
    wxButton* m_btnSend;
////@end ConnectDlg member variables
	
	
private:
	wxSocketClient m_client;
	wxString  m_ip;
	unsigned int m_port;

};

#endif
    // _CONNECTDLG_H_
