/////////////////////////////////////////////////////////////////////////////
// Name:        connectdlg.cpp
// Purpose:     
// Author:      CodeSoul
// Modified by: 
// Created:     29/05/2015 10:33:48
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 29/05/2015 10:33:48

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "connectdlg.h"

////@begin XPM images
////@end XPM images


/*
 * ConnectDlg type definition
 */

//IMPLEMENT_DYNAMIC_CLASS( ConnectDlg, wxDialog )


/*
 * ConnectDlg event table definition
 */

BEGIN_EVENT_TABLE( ConnectDlg, wxDialog )

////@begin ConnectDlg event table entries
    EVT_CLOSE( ConnectDlg::OnCloseWindow )
    EVT_BUTTON( ID_BTN_SEND, ConnectDlg::OnBtnSendClick )
////@end ConnectDlg event table entries

END_EVENT_TABLE()


/*
 * ConnectDlg constructors
 */
 /*
ConnectDlg::ConnectDlg()
{
    Init();
}
//*/

ConnectDlg::ConnectDlg( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    Init();
    Create(parent, id, caption, pos, size, style);
}


/*
 * ConnectDlg creator
 */

bool ConnectDlg::Create( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
	wxASSERT(!m_ip.IsNull());
	wxIPV4address ipAddr;
	ipAddr.Hostname(m_ip);
	ipAddr.Service(m_port);
	if (!m_client.Connect(ipAddr))
	{
		wxMessageBox("Connect failue.");
		return this->Destroy();
	}

////@begin ConnectDlg creation
    SetExtraStyle(wxWS_EX_VALIDATE_RECURSIVELY|wxWS_EX_BLOCK_EVENTS);
    wxDialog::Create( parent, id, caption, pos, size, style );

    CreateControls();
    if (GetSizer())
    {
        GetSizer()->SetSizeHints(this);
    }
    Centre();
////@end ConnectDlg creation

    return true;
}


/*
 * ConnectDlg destructor
 */

ConnectDlg::~ConnectDlg()
{
////@begin ConnectDlg destruction
////@end ConnectDlg destruction
}


/*
 * Member initialisation
 */

void ConnectDlg::Init()
{
////@begin ConnectDlg member initialisation
    m_txContent = NULL;
    m_btnSend = NULL;
////@end ConnectDlg member initialisation
}


/*
 * Control creation for ConnectDlg
 */

void ConnectDlg::CreateControls()
{    
////@begin ConnectDlg content construction
    // Generated by DialogBlocks, 02/06/2015 12:44:41 (unregistered)

    ConnectDlg* itemDialog1 = this;

    wxBoxSizer* itemBoxSizer2 = new wxBoxSizer(wxVERTICAL);
    itemDialog1->SetSizer(itemBoxSizer2);

    m_txContent = new wxTextCtrl( itemDialog1, ID_TEXT_CONTENT, wxEmptyString, wxDefaultPosition, wxSize(300, 200), wxTE_MULTILINE );
    itemBoxSizer2->Add(m_txContent, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5);

    m_btnSend = new wxButton( itemDialog1, ID_BTN_SEND, _("Send"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer2->Add(m_btnSend, 0, wxALIGN_RIGHT|wxALL, 5);

////@end ConnectDlg content construction
}


/*
 * Should we show tooltips?
 */

bool ConnectDlg::ShowToolTips()
{
    return true;
}

/*
 * Get bitmap resources
 */

wxBitmap ConnectDlg::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin ConnectDlg bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end ConnectDlg bitmap retrieval
}

/*
 * Get icon resources
 */

wxIcon ConnectDlg::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin ConnectDlg icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end ConnectDlg icon retrieval
}

/*
 * wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BTN_SEND
 */

void ConnectDlg::OnBtnSendClick( wxCommandEvent& event )
{
	wxString content = m_txContent->GetValue();
	m_client.Write(content.mb_str(), content.Length());
	if (m_client.Error())
	{
		wxLogMessage("Send message error");
	}
	else
	{
		wxLogMessage("Send a message: %s", content);
	}
////@begin wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BTN_SEND in ConnectDlg.
    // Before editing this code, remove the block markers.
    event.Skip();
////@end wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BTN_SEND in ConnectDlg. 
}


/*
 * wxEVT_CLOSE_WINDOW event handler for ID_CONNECTDLG
 */

void ConnectDlg::OnCloseWindow( wxCloseEvent& event )
{
	m_client.Close();
////@begin wxEVT_CLOSE_WINDOW event handler for ID_CONNECTDLG in ConnectDlg.
    // Before editing this code, remove the block markers.
    event.Skip();
////@end wxEVT_CLOSE_WINDOW event handler for ID_CONNECTDLG in ConnectDlg. 
}

