/////////////////////////////////////////////////////////////////////////////
// Name:        maindlg.h
// Purpose:     
// Author:      CodeSoul
// Modified by: 
// Created:     28/05/2015 17:32:20
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 28/05/2015 17:32:20

#ifndef _MAINDLG_H_
#define _MAINDLG_H_


/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_MAINDLG 10000
#define ID_TEXT_LOG 10001
#define ID_TEXT_IP 10003
#define ID_TEXT_PORT 10004
#define ID_BTN_CONNECT 10002
#define SYMBOL_MAINDLG_STYLE wxCAPTION|wxSYSTEM_MENU|wxCLOSE_BOX|wxMINIMIZE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_MAINDLG_TITLE _("Cloud Client")
#define SYMBOL_MAINDLG_IDNAME ID_MAINDLG
#define SYMBOL_MAINDLG_SIZE wxSize(400, 300)
#define SYMBOL_MAINDLG_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * MainDlg class declaration
 */

class MainDlg: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( MainDlg )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    MainDlg();
    MainDlg( wxWindow* parent, wxWindowID id = SYMBOL_MAINDLG_IDNAME, const wxString& caption = SYMBOL_MAINDLG_TITLE, const wxPoint& pos = SYMBOL_MAINDLG_POSITION, const wxSize& size = SYMBOL_MAINDLG_SIZE, long style = SYMBOL_MAINDLG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_MAINDLG_IDNAME, const wxString& caption = SYMBOL_MAINDLG_TITLE, const wxPoint& pos = SYMBOL_MAINDLG_POSITION, const wxSize& size = SYMBOL_MAINDLG_SIZE, long style = SYMBOL_MAINDLG_STYLE );

    /// Destructor
    ~MainDlg();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

	void Log(const char *log);
	void LogLine(const char *log);

////@begin MainDlg event handler declarations

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BTN_CONNECT
    void OnBtnConnectClick( wxCommandEvent& event );

////@end MainDlg event handler declarations

////@begin MainDlg member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end MainDlg member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin MainDlg member variables
    wxTextCtrl* m_txLog;
    wxTextCtrl* m_txIP;
    wxTextCtrl* m_txPort;
    wxButton* m_btnConnect;
////@end MainDlg member variables
};

#endif
    // _MAINDLG_H_
